// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnvfirchbtmnczlypgyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpudmZpcmNoYnRtbmN6bHlwZ3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjY4MjIsImV4cCI6MjA2ODE0MjgyMn0.duZF-A3a9DTYnQISQrXJlOPlyk93ygsGoKd6p6OdRvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});